const assetPath = (path) => `${import.meta.env.BASE_URL}${path.replace(/^\//, "")}`;

export const boxCatalog = [
  {
    slug: "past-box",
    arabicName: "صندوق الماضي",
    name: "The Past Box",
    tagline: "Memory & Reflection",
    theme: "sand",
    price: 280,
    itemCount: 9,
    summary:
      "A nostalgic box built around scent, sound, handwriting, and personal storytelling so elders can revisit meaningful parts of their lives with family.",
    items: [
      {
        name: "Customized photo album",
        note: "A keepsake album personalized for the elder, designed to spark memory recall through familiar faces and moments.",
        sprite: assetPath("/mockups/past-box-items.png"),
        position: "left top",
      },
      {
        name: "\"My Story\" notebook",
        note: "A premium notebook for life stories, reflections, and handwritten memories.",
        sprite: assetPath("/mockups/past-box-items.png"),
        position: "center top",
      },
      {
        name: "Memory question cards",
        note: "Open-ended conversation prompts designed to bring stories forward naturally.",
        sprite: assetPath("/mockups/past-box-items.png"),
        position: "right top",
      },
      {
        name: "Vintage-style mini radio",
        note: "A tactile nostalgic object that brings familiar sound and comfort into the experience.",
        sprite: assetPath("/mockups/past-box-items.png"),
        position: "left center",
      },
      {
        name: "Curated Arabic songs",
        note: "A Judhoor-branded music piece that connects memory to emotion and era.",
        sprite: assetPath("/mockups/past-box-items.png"),
        position: "center center",
      },
      {
        name: "Bakhoor scent trigger",
        note: "A scent-based memory prompt that taps into familiarity and atmosphere.",
        sprite: assetPath("/mockups/past-box-items.png"),
        position: "center bottom",
      },
      {
        name: "Family story prompt cards",
        note: "Conversation prompts that help grandchildren and caregivers invite deeper family storytelling with ease.",
        sprite: assetPath("/mockups/past-box-items.png"),
        position: "right center",
      },
      {
        name: "Memory keepsake envelope",
        note: "A special place for storing small notes, photographs, or written reflections gathered over time.",
        sprite: assetPath("/mockups/past-box-items.png"),
        position: "left bottom",
      },
      {
        name: "Family guide card",
        note: "A gentle guide that helps relatives use the box in a respectful, dementia-friendly, and meaningful way.",
        sprite: assetPath("/mockups/past-box-items.png"),
        position: "right bottom",
      },
    ],
    images: [
      assetPath("/mockups/past-box-hero-new.png"),
      assetPath("/mockups/past-box-items.png"),
      assetPath("/mockups/past-box-detail.png"),
    ],
  },
  {
    slug: "balance-box",
    arabicName: "صندوق التوازن",
    name: "Balance Box",
    tagline: "Health & Wellbeing",
    theme: "sage",
    price: 280,
    itemCount: 9,
    summary:
      "A soothing box that encourages healthy daily habits, gentle movement, hydration, comfort, and emotional calm through familiar premium objects.",
    items: [
      {
        name: "Stress ball",
        note: "A soft branded stress ball that supports hand mobility and calm tactile release.",
        sprite: assetPath("/mockups/balance-box-items.png"),
        position: "left top",
      },
      {
        name: "Customized water bottle",
        note: "A premium hydration object designed to feel elegant enough to keep nearby every day.",
        sprite: assetPath("/mockups/balance-box-items.png"),
        position: "center top",
      },
      {
        name: "Stretching band",
        note: "A gentle movement tool for seated or standing routines with accessible daily use.",
        sprite: assetPath("/mockups/balance-box-items.png"),
        position: "right top",
      },
      {
        name: "Prayer beads",
        note: "A culturally familiar grounding object that adds comfort, rhythm, and spiritual calm.",
        sprite: assetPath("/mockups/balance-box-items.png"),
        position: "left center",
      },
      {
        name: "Linen sleep mask",
        note: "A soft comfort piece for rest and relaxation in the Judhoor palette.",
        sprite: assetPath("/mockups/balance-box-items.png"),
        position: "center center",
      },
      {
        name: "Wellbeing reminder cards",
        note: "Gentle visual cues for hydration, rest, and simple habits that support daily wellbeing.",
        sprite: assetPath("/mockups/balance-box-items.png"),
        position: "center bottom",
      },
      {
        name: "Aromatherapy sachet",
        note: "A calming scent object chosen to soften the atmosphere and support restful moments.",
        sprite: assetPath("/mockups/balance-box-items.png"),
        position: "right center",
      },
      {
        name: "Comfort tea sachets",
        note: "A soothing tea pairing that supports a slower daily rhythm and a more grounded routine.",
        sprite: assetPath("/mockups/balance-box-items.png"),
        position: "left bottom",
      },
      {
        name: "Family guide card",
        note: "A supportive guide with simple suggestions for helping elders engage in calm daily wellbeing rituals.",
        sprite: assetPath("/mockups/balance-box-items.png"),
        position: "right bottom",
      },
    ],
    images: [
      assetPath("/mockups/balance-box-hero.png"),
      assetPath("/mockups/balance-box-items.png"),
      assetPath("/mockups/balance-box-detail.png"),
    ],
  },
  {
    slug: "important-box",
    arabicName: "صندوق أنت مهمة",
    name: "You Are Important Box",
    tagline: "Connection & Love",
    theme: "rose",
    price: 280,
    itemCount: 11,
    summary:
      "An emotionally rich box built around letters, photographs, voice messages, keepsakes, and shared writing to deepen intergenerational love.",
    items: [
      {
        name: "Letters from grandchildren",
        note: "Handwritten letters that give the box its most intimate emotional weight.",
        sprite: assetPath("/mockups/important-box-items.png"),
        position: "left top",
        previewPosition: "8% 12%",
        previewSize: "185% 185%",
      },
      {
        name: "Family photo frame",
        note: "A bedside keepsake designed to hold a loved family portrait at the center of the room.",
        sprite: assetPath("/mockups/important-box-items.png"),
        position: "center top",
        previewPosition: "37% 12%",
        previewSize: "190% 190%",
      },
      {
        name: "Reasons We Love You jar",
        note: "Rolled notes of affection that can be opened one by one across many days.",
        sprite: assetPath("/mockups/important-box-items.png"),
        position: "center center",
        previewPosition: "38% 46%",
        previewSize: "195% 195%",
      },
      {
        name: "\"Open When\" letter bundle",
        note: "A set of lovingly timed letters for loneliness, missing family, or wanting comfort.",
        sprite: assetPath("/mockups/important-box-items.png"),
        position: "right center",
        previewPosition: "76% 48%",
        previewSize: "190% 190%",
      },
      {
        name: "QR voice message card",
        note: "A premium printed card that links directly to a recorded family message.",
        sprite: assetPath("/mockups/important-box-items.png"),
        position: "left bottom",
        previewPosition: "14% 82%",
        previewSize: "195% 195%",
      },
      {
        name: "Shared journal",
        note: "A collaborative writing object that lets generations answer one another over time.",
        sprite: assetPath("/mockups/important-box-items.png"),
        position: "right bottom",
        previewPosition: "84% 82%",
        previewSize: "190% 190%",
      },
      {
        name: "Printed family photographs",
        note: "A small curated set of family photos that make the box feel immediately personal and lived-in.",
        sprite: assetPath("/mockups/important-box-items.png"),
        position: "right top",
        previewPosition: "72% 14%",
        previewSize: "190% 190%",
      },
      {
        name: "Scented comfort candle",
        note: "A warm decorative candle that adds softness, atmosphere, and emotional calm to the experience.",
        sprite: assetPath("/mockups/important-box-items.png"),
        position: "center bottom",
        previewPosition: "72% 18%",
        previewSize: "220% 220%",
      },
      {
        name: "Keepsake note cards",
        note: "Blank premium cards for adding more messages of love over time instead of treating the box as one-time use.",
        sprite: assetPath("/mockups/important-box-items.png"),
        position: "center center",
        previewPosition: "62% 80%",
        previewSize: "220% 220%",
      },
      {
        name: "Memory envelope set",
        note: "A set of decorative envelopes for storing photographs, letters, or small sentimental notes.",
        sprite: assetPath("/mockups/important-box-items.png"),
        position: "left center",
        previewPosition: "16% 48%",
        previewSize: "200% 200%",
      },
      {
        name: "Family guide card",
        note: "A guide for helping family members turn the box into a repeatable ritual of affection and reassurance.",
        sprite: assetPath("/mockups/important-box-items.png"),
        position: "center top",
        previewPosition: "86% 60%",
        previewSize: "230% 230%",
      },
    ],
    images: [
      assetPath("/mockups/important-box-hero-new.png"),
      assetPath("/mockups/important-box-items.png"),
    ],
  },
  {
    slug: "travel-box",
    arabicName: "صندوق السفر",
    name: "Travel Box",
    tagline: "Travel & Discovery",
    theme: "midnight",
    price: 280,
    itemCount: 11,
    summary:
      "An Egypt-inspired discovery box built around heritage, ancient games, scent, story cards, and keepsake objects that bring travel into the home.",
    items: [
      {
        name: "Nile flooding story cards",
        note: "A tied deck of cultural cards introducing Nile flooding, agriculture, and heritage prompts for family conversation.",
        sprite: assetPath("/mockups/travel-box-items.jpg"),
        position: "left top",
        previewPosition: "61% 12%",
        previewSize: "260% 260%",
      },
      {
        name: "Mini felucca boat",
        note: "A small Nile sailboat model that gives the box a tactile travel object and a clear visual sense of place.",
        sprite: assetPath("/mockups/travel-box-items.jpg"),
        position: "left center",
        previewPosition: "84% 18%",
        previewSize: "300% 300%",
      },
      {
        name: "Sphinx heritage figurine",
        note: "A sculptural keepsake inspired by ancient Egyptian heritage, chosen as a strong memory and storytelling anchor.",
        sprite: assetPath("/mockups/travel-box-items.jpg"),
        position: "right center",
        previewPosition: "32% 44%",
        previewSize: "270% 270%",
      },
      {
        name: "Ancient stone tablet",
        note: "A textured tablet-style object that adds a tactile archaeological feeling to the travel ritual.",
        sprite: assetPath("/mockups/travel-box-items.jpg"),
        position: "right top",
        previewPosition: "57% 48%",
        previewSize: "260% 260%",
      },
      {
        name: "Canopic jar miniature set",
        note: "A set of small Egyptian-inspired jars that encourage curiosity, naming, sorting, and shared cultural discussion.",
        sprite: assetPath("/mockups/travel-box-items.jpg"),
        position: "center bottom",
        previewPosition: "77% 45%",
        previewSize: "275% 275%",
      },
      {
        name: "Engraved Egyptian pen",
        note: "A premium writing object for notes, reflections, or answering the included story prompts.",
        sprite: assetPath("/mockups/travel-box-items.jpg"),
        position: "right center",
        previewPosition: "82% 55%",
        previewSize: "300% 300%",
      },
      {
        name: "Hieroglyphic leather journal",
        note: "A leather-style travel journal for writing memories, imagined journeys, and family reflections.",
        sprite: assetPath("/mockups/travel-box-items.jpg"),
        position: "left bottom",
        previewPosition: "13% 72%",
        previewSize: "245% 245%",
      },
      {
        name: "Ancient board game",
        note: "A heritage-inspired game board with pieces, designed to invite gentle play and interaction.",
        sprite: assetPath("/mockups/travel-box-items.jpg"),
        position: "center bottom",
        previewPosition: "34% 76%",
        previewSize: "255% 255%",
      },
      {
        name: "Egyptian musk bottle",
        note: "A small scent bottle that brings aroma into the travel experience and creates a sensory memory cue.",
        sprite: assetPath("/mockups/travel-box-items.jpg"),
        position: "left bottom",
        previewPosition: "33% 90%",
        previewSize: "310% 310%",
      },
      {
        name: "Nile water keepsake jar",
        note: "A labeled keepsake jar that adds a playful, museum-like discovery moment to the package.",
        sprite: assetPath("/mockups/travel-box-items.jpg"),
        position: "center bottom",
        previewPosition: "43% 90%",
        previewSize: "310% 310%",
      },
      {
        name: "Frankincense and myrrh pouch",
        note: "A scented pouch that adds warmth, texture, and a heritage-inspired fragrance ritual.",
        sprite: assetPath("/mockups/travel-box-items.jpg"),
        position: "right bottom",
        previewPosition: "62% 88%",
        previewSize: "280% 280%",
      },
    ],
    images: [
      assetPath("/mockups/travel-box-hero-4k.png"),
      assetPath("/mockups/travel-box-items.jpg"),
    ],
  },
];

export const conceptMoments = [
  {
    title: "Packaging that feels ceremonial",
    description:
      "The drawer-style presentation and foil details make every unboxing feel intentional and honoring.",
    image: assetPath("/mockups/past-box-hero-new.png"),
  },
  {
    title: "Objects that invite interaction",
    description:
      "Every object is tactile, accessible, and selected to create a gentle moment rather than a forced task.",
    image: assetPath("/mockups/important-box-items.png"),
  },
  {
    title: "A wider brand world",
    description:
      "The Travel Box extends Judhoor into heritage-led discovery through tactile Egyptian-inspired objects.",
    image: assetPath("/mockups/travel-box-items.jpg"),
  },
];

export const journeySteps = [
  {
    kicker: "01",
    title: "Choose the emotional need",
    description:
      "Start with reflection, wellbeing, discovery, or connection depending on what the elder needs most.",
  },
  {
    kicker: "02",
    title: "Unbox with dignity",
    description:
      "The visual language is soft, premium, and familiar so the experience feels honoring from the first glance.",
  },
  {
    kicker: "03",
    title: "Use the family guide",
    description:
      "Caregivers and relatives are gently guided toward supportive interaction without pressure or infantilization.",
  },
  {
    kicker: "04",
    title: "Repeat the ritual",
    description:
      "The boxes are designed to be revisited, creating a rhythm of care rather than a one-time activity.",
  },
];
